LOG_LEVEL: "debug"
LOG_DEVELOPMENT: false
LOG_DISABLE_CALLER: false
LOG_DISABLE_STACKTRACE: false
LOG_ENCODING: "json"
LOG_OUTPUT_PATHS: "stdout"
LOG_ERROR_OUTPUT_PATHS: "stderr"

DOCS_PATH: "./docs"
SERVER_PORT: 8081
READ_TIMEOUT_MS: 2000
WRITE_TIMEOUT_MS: 2000

REDIS_HOST: "localhost"
REDIS_PORT: 6379
REDIS_POOL_SIZE: 10
REDIS_DIAL_TIMEOUT: 200
REDIS_READ_TIMEOUT: 200
REDIS_WRITE_TIMEOUT: 200
REDIS_IDLE_TIMEOUT: 200

DB_DRIVER: postgres
DB_NAME: go_skeleton
DB_HOST: postgres-db
DB_USER: postgres
DB_PASSWORD: postgres
DB_PORT: 5432
DB_POOL_SIZE: 20
DB_READ_TIMEOUT_MS: 200
DB_WRITE_TIMEOUT_MS: 200
DB_CONNECTION_MAX_LIFETIME_MINUTE: 20