REDIS_HOST: "localhost"
REDIS_PORT: 1997
REDIS_POOL_SIZE: 0
REDIS_DIAL_TIMEOUT: 200
REDIS_READ_TIMEOUT: 200
REDIS_WRITE_TIMEOUT: 200
REDIS_IDLE_TIMEOUT: 200

DB_DRIVER: postgres
DB_NAME: test-db
DB_HOST: localhost
DB_USER: postgres
DB_PASSWORD: postgres
DB_PORT: 1998
DB_POOL_SIZE: 20
DB_READ_TIMEOUT_MS: 200
DB_WRITE_TIMEOUT_MS: 200
DB_CONNECTION_MAX_LIFETIME_MINUTE: 20

LOG_LEVEL: "debug"
LOG_DEVELOPMENT: false
LOG_DISABLE_CALLER: false
LOG_DISABLE_STACKTRACE: false
LOG_ENCODING: "json"
LOG_OUTPUT_PATHS: "stdout"
LOG_ERROR_OUTPUT_PATHS: "stderr"