swagger: '2.0'
info:
  description: go-swagger
  title: go-swagger
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http

paths:

definitions:
  ErrorResponse:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      message_title:
        type: string
      message_severity:
        type: string
  BadRequest:
    type: object
    properties:
      status_code:
        type: integer
      data:
        type: object
      success:
        type: boolean
        default: false
      errors:
        $ref: "#/definitions/ErrorResponse"
  Unauthorised:
    type: object
    properties:
      status_code:
        type: integer
      data:
        type: object
      success:
        type: boolean
        default: false
      errors:
        $ref: "#/definitions/ErrorResponse"